#![allow(clippy::let_unit_value)]

use diesel_migrations::EmbeddedMigrations;
use lalrpop_util::lalrpop_mod;

lalrpop_mod!(pub cmd);

pub const MIGRATIONS: EmbeddedMigrations =
    diesel_migrations::embed_migrations!("migrations");

pub mod auth;
pub mod config;
pub mod msg;
pub mod permission;
/// Contains the database schema generated by diesel.
pub mod schema;
/// Application state. This includes the database pool.
pub mod state;
/// Templating code.
pub mod template;
pub mod tournaments;
pub mod util_resp;
/// Code for validating data input to the tab system.
pub mod validation;
pub mod widgets;
