use diesel_migrations::EmbeddedMigrations;
use rocket::launch;

use crate::config::make_rocket;

pub const MIGRATIONS: EmbeddedMigrations = diesel_migrations::embed_migrations!("migrations");

pub mod auth;
pub mod config;
pub mod permission;
/// Contains the database schema generated by diesel.
pub mod schema;
/// Application state. This includes the database pool.
pub mod state;
/// Templating code.
pub mod template;
pub mod tournaments;
/// Code for validating data input to the tab system.
pub mod validation;

pub mod msg;

#[launch]
async fn launch() -> _ {
    make_rocket()
}
